### ISSUE TITLE
Readme/Spec: Drop Feature FS (`for` statements)

### ISSUE THREAD

**Issue by js-choi** [js-choi/proposal-smart-pipelines#19]

**Comment by tabatkins** [comment]
I'm less sure of the value of this.  It's a slight syntax convenience for `for` loops when the name of the iterated vals isn't very important, but it *looks* like it's allowing a more general pipeline-over-iterables functionality.  Unfortunately, it can only be used to *start* a pipeline, rather than showing up in the middle of one, and it doesn't *result* in a pipeline either - it's still a for-loop statement, rather than a pipeline expression that results in a value.

I'm feeling like this should be rejected, in favor of later letting pipelines opt into lifting over the input value.  (This would also address a bunch more things, like pipelining over promises by having the pipeline resolve to a promise, rather than having the whole outer function become async.)

(As discussed in IRC previously, topic-form allows for reasonable handling of most lifting all by itself, with `xs |> #.map(fn)`. The big thing missing is a built-in way to do this over general iterables, without first splatting it into an array. That might be worth syntax.)

**Comment by js-choi** [comment]
@tabatkins Thanks for the comment. This is very valuable feedback. I haven’t really looked for real-world examples for Feature FS in the explainer’s motivation section, but I plan to later. But it is good to know that I might want to deprioritize or drop.

> Unfortunately, it can only be used to start a pipeline, rather than showing up in the middle of one, and it doesn't result in a pipeline either - it's still a for-loop statement, rather than a pipeline expression that results in a value.

It may be valuable to eventually have a pipeline form similar to `for`–`of` that gathers iterated elements, as if it were a list comprehension. Perl 6 has such a `gather … { … }` expression, for instance. Though perhaps with block parameters it wouldn’t matter as much. 

Yeah, Feature FS probably should be dropped for now.  `try`/`catch`/`finally` pipelines (#18), I hope, would be more useful…

**Comment by tabatkins** [comment]
Hm, yeah, block parameters might suffice here - `xs |> {for(x of #) { ... }}`. Still need some annoying boilerplate if you're wanting to just do a `#.map()` but have to deal with a general iterable, but maybe that's okay.
