### ISSUE TITLE
How would this interop with stateful closures?

### ISSUE THREAD

**Issue by dead-claudia** [js-choi/proposal-smart-pipelines#24]
To leave a particular example, how would this interoperate with stateful primitive-like operators like `distinct` or `scan`? I know it's not directly related to this proposal, but [if we go with my lifted pipeline strawman](https://github.com/isiahmeadows/lifted-pipeline-strawman) as an extension of this, how would it interop with them? (The current syntax offers no convenient escape hatch to break the "smart" default, instead [requiring a new name to be assigned](https://martinfowler.com/bliki/TwoHardThings.html).)

```js
// Usage
books >:> distinct() >:> console.log(#)

// Implementation
function distinct(by = Object.is) {
    let hasPrev = false, prev
    return x => {
        const memo = hasPrev
        hasPrev = true
        return memo || by(prev, prev = x) ? [x] : []
    }
}
```

**Comment by js-choi** [comment]
See also isiahmeadows/lifted-pipeline-strawman#6.

***

Pasting from https://github.com/js-choi/proposal-smart-pipelines/issues/16#issuecomment-375901012:

> As a parenthetical follow-up to https://github.com/tc39/proposal-pipeline-operator/issues/106#issuecomment-373455338, I am very interested in your own proposal. I think there’s a lot of potential there. I’m still chewing over it as I work out the formal specifications of the remaining additional features, because it’s a big problem. I’ll reply in your new issue #24 when I can.

***

Also pasting from https://github.com/tc39/proposal-pipeline-operator/issues/106#issuecomment-373452668 because still relevant:

> As long as we’re talking about useful abstractions from Haskell and category theory, I think it’s important to choose the right level of abstraction here for nested/plural/etc. data.
>
> I need to think about it more, but…have you considered other abstractions, other than functor mapping, such as applicative application or monadic binding—or, as I am currently most interested in exploring, eventually extending smart pipelines into something like the `proc` notation of [arrows](https://en.wikibooks.org/wiki/Haskell/Understanding_arrows) or maybe [Kleisli composition](https://blog.ssanj.net/posts/2017-06-07-composing-monadic-functions-with-kleisli-arrows.html).
>
> …I’m interested in extending smart pipelines to support abstractions more powerful than functor mapping—like [static arrows or Kleisli arrows](https://en.wikibooks.org/wiki/Haskell/Understanding_arrows) and [Kleisli composition](https://blog.ssanj.net/posts/2017-06-07-composing-monadic-functions-with-kleisli-arrows.html)—especially for the purpose of tersely using lenses or [Clojure-style transducers](https://github.com/jlongster/transducers.js/). To use your `uniq` example, this, in turn, might enable defining a `uniq` transducer that could work on reducible/plural data of any type—without unnecessary intermediate allocation, when combined with other transducers such as those for mapping, filtering, partitioning, taking/leaving/slicing, and so on. But right now I’m dealing with implementing and specifying smart pipelines themselves, so I haven’t been able to really work out how this would work in JavaScript.

From the lifted-pipeline proposal: [example of syntax for simple monads](https://github.com/isiahmeadows/lifted-pipeline-strawman/blob/master/README.md#syntax-for-loops-and-pipeline-manipulation).

***

With regard to Clojure-style transducers, which comprise an [example of stateful closures that lift an abstraction](https://hypirion.com/musings/haskell-transducers): jlongster/transducers.js#22 and jlongster/transducers.js#51, as a problem of extending its transducer model to the async structures from [kriskowal/gtor](https://github.com/kriskowal/gtor).

Also leaving here for other readers: Related on the Clojure side, [Specter](https://github.com/nathanmarz/specter). (Frequently isomorphically on the Haskell side, [lenses](https://www.youtube.com/watch?v=T88TDS7L5DY), traversables, foldables, as mentioned above.)

***

I’ll follow up after I finish <del>#17 and #18</del><ins>#25</ins>. Thanks again for the outreach; your proposal is very interesting.

**Comment by js-choi** [comment]
Thanks for the issue; sorry about the delayed reply.

After talking more with Tab Atkins and Daniel Ehrenberg, we’ve decided to archive this proposal in favor of a [simpler Hack-pipes proposal][Hack pipes], which is a subset of this proposal.

Feel free to open a new issue in the new repository if you think it still applies.

[Hack pipes]: https://github.com/js-choi/proposal-hack-pipes/
