### ISSUE TITLE
Why was `#` chosen as the topic reference?

### ISSUE THREAD

**Issue by szhu** [js-choi/proposal-smart-pipelines#29]
Q1
Can we use/is there a reason why we can't use `this` as the topic reference keyword instead of `#`? I think that the current use of `this` in JavaScript and the topic reference here are analogous. In addition, consider that this proposal would in practice cover many of the same use cases as the [bind operator proposal](https://github.com/tc39/proposal-bind-operator), which uses `this` in the spot analogous to where `#` is used here.

Q2
Why was `#` chosen in particular?

**Comment by mAAdhaTTah** [comment]
1. We can't, because `|> this.hello` would be ambiguous (does it refer to a method on the current `this` context or does it refer to the topic?). Adding an additional rule where `this` can change is also definitely confusing (as if `this` isn't confusing enough).

2. It's not officially settled. `#` was chosen as an initial placeholder, but both `@` & `%` have been floated as alternatives. We didn't want to bikeshed the token before we decided we were going with this proposal in particular.

**Comment by szhu** [comment]
For 1., can we make that not ambiguous and make the `this` in `|> this.hello` always refer to the topic? Something similar happens when you have nested functions: In `function() { (function() {this.hello})() }`, `this` always refers to the innermost scope that gives a meaning to `this`.

**Comment by mAAdhaTTah** [comment]
You _could_ but I think that's likely to be a footgun and won't get through committee.

**Comment by szhu** [comment]
Can you explain why?

It looks like if

```js
[1,2,3] |> _.filter(this, (x) => x > 2)
```

should desugar to 

```js
(function() {
  _.filter(this, (x) => x > 2)
}).call([1,2,3])
```

then `this` is doing exactly the same thing in both places.

**Comment by mAAdhaTTah** [comment]
It's not that it's ambiguous from a grammar perspective; it's that it's confusing to developers, and it would be a 5th new rule for defining what `this` is.

```js
class Something {
  removeDuplicates(data) {
    return data.filter(/* logic */);
  }

  fixData() {
    // This would actually desugar to this.data.removeDuplicates()
    // instead of this.removeDuplicates(this.data)
    return this.data |> this.removeDuplicates
  }
}
```

**Comment by szhu** [comment]
Okay I see. Can we get rid of the topic reference this way instead?

From this proposal:
```js
promise
|> await #
|> # || throw new TypeError(
  `Invalid value from ${promise}`)
|> doubleSay(#, ', ')
|> capitalize
|> # + '!'
|> new User.Message(#)
|> await stream.write(#)
|> console.log;
```

My proposal:
```js
promise
|> await
|> x => x || throw new TypeError(
  `Invalid value from ${promise}`)
|> x => doubleSay(x, ', ')
|> capitalize
|> x => x + '!'
|> x => new User.Message(x)
|> async x => await stream.write(x)
|> console.log;
```

Rationale: I think that unlikely for a single-symbol keyboard -- `#`, `%`, `?`, or otherwise -- to get past the committee. My proposal still allows the user to define their own one-letter "symbol" if they want to keep it short.

**Comment by mAAdhaTTah** [comment]
Almost. That's basically the [F# Pipeline](https://github.com/valtech-nyc/proposal-fsharp-pipelines/), although this won't work the way you expect:

```js
|> async x => await stream.write(x)
```

as the async function will still return a promise to the next step. It becomes this in F#:

```js
|> x => new User.Message(x)
|> x => stream.write(x)
|> await
|> console.log;
```

**Comment by js-choi** [comment]
Indeed, `#` is just a preliminary choice. There are some other choices like `?`, `%`, and `@` that are also possible. There’s been discussion about this in tc39/proposal-pipeline-operator#91. Hopefully, everyone will be able to experiment with all of those possible choices once the Babel plugin gets finished. I’ve tried to make this clearer in the readme now. 

Thanks to @mAAdhaTTah for addressing this question while I’ve been busy; I’m really thankful. 

I do want to also point out that there’s another trade-off of relying on IFFEs in the F# proposal. Not only would you have to put in `x =>` for each IFFE step—you also would have to wrap them in parentheses. The code in https://github.com/js-choi/proposal-smart-pipelines/issues/29#issuecomment-425565642 would thus, in the F# proposal, have to be:

```js
promise
|> await
|> (x => x || throw new TypeError(
  `Invalid value from ${promise}`))
|> (x => doubleSay(x, ', '))
|> capitalize
|> (x => x + '!')
|> (x => new User.Message(x))
|> (async x => await stream.write(x))
|> console.log;
```

The F# proposal is designed like this because [otherwise you would not be able to use them within arrow functions without parentheses](https://github.com/valtech-nyc/proposal-fsharp-pipelines/#arrow-functions--parentheses) (that is, `x => x |> f` would otherwise be invalid). Everything has advantages and disadvantages—@mAAdhaTTah and I been trying to balance these fundamental trade-offs in various ways together and see what happens.

It may end up that this is worth it, but it’s something worth keeping in mind.

Anyways, I’ve edited the readme to point to tc39/proposal-pipeline-operator#91. Hopefully that addresses this question for now.
